### ISSUE TITLE
Research for suitable technologies and provide architectural decision

### ISSUE THREAD

**Issue by VeronikaValentinova** [VeronikaValentinova/nbu-planning#1]
### Introduction ###

Provide research details for suitable technologies capable to fit best the needs of the application.
Choosing the architecture of the application.

### Details ###

The scope of the research should cover: 
- FrontEnd
- BackEnd
- Database

Providing the architectural decision should include all interconnections between modules.

**Comment by martinNegriev** [comment]
FrontEnd - Javascript, HTML, CSS, Angular
BackEnd - Java(Spring Boot)
Database - SQL db with MySQL
