### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by VeronikaValentinova** [VeronikaValentinova/nbu-planning#7]
### General ###
The system should operate with two types of Roles - **Admin** and **User**.

### Details ###

Every person using the system should log in as an Admin or User.
If the person decides to log in as Admin fields for providing username and password should be available.
If the person decides to log in as User additional form for **new user** should be available. 

### Acceptance Criteria ###

1. **Given** Person decides to log in as Admin
**When** Person enters correctly username and password
**Then** Authentication is successful as admin

2. **Given** Person decides to log in as Admin
**When** Person enters wrong username and password
**Then** Authentication is not successful

3. **Given** Person decides to log in as User
**When** Person enters correctly username and password
**Then** Authentication is successful as user

4. **Given** Person decides to log in as User
**When** Person enters wrong username and password
**Then** Authentication is not successful

2. **Given** Person decides to log in as User
**When** Person decides to create new account
**Then** Type for new account is shown

### Definition of Done ###

1. Code is approved by at least 2 members
2. Acceptance criteria are met
3. All unit tests passed

**Comment by martinNegriev** [comment]
We decided to pick a specific e-mail for the ADMIN, which means, only one user account can be an ADMIN. If more are needed, the logic could be added. Other than that, other users are given "USER" roles by default.
