### ISSUE TITLE
Create new user account

### ISSUE THREAD

**Issue by VeronikaValentinova** [VeronikaValentinova/nbu-planning#8]
### General ###
As a **User**, I would like to be able to create myself a new account, so that I would be able to access information about films and post new data as well.

### Details ###

When the view for login as a user is chosen - there should be an option to register a new one.

To register, the user should fill-in their first and last name, email and years. 
All four fields are required.

### Acceptance Criteria ###

1. **Given** Person decides to register in the system
**When** Person fills-in all required fields
**Then**Registration is successful

2. **Given** Person decides to register in the system
**When** Person leaves empty one required field
**Then** Person cannot proceed with the registration

### Definition of Done ###

1. Code is approved by at least 2 members
2. Acceptance criteria are met
3. All unit tests passed

**Comment by martinNegriev** [comment]
All criterias are met.
